#define T_ID                               1
#define T_EDGEPT                           2
#define T_OF                               3
#define T_PLUS                             4
#define T_MINUS                            5
#define T_STAR                             6
#define T_SLASH                            7
#define T_PERCENT                          8
#define T_UMINUS                           9
#define T_EOL                             10
#define T_ASSIGN                          11
#define T_PLACENAME                       12
#define T_COLON                           13
#define T_ASSERT                          14
#define T_LP                              15
#define T_EQ                              16
#define T_RP                              17
#define T_DEFINE                          18
#define T_CODEBLOCK                       19
#define T_FILL                            20
#define T_COLOR                           21
#define T_THICKNESS                       22
#define T_PRINT                           23
#define T_STRING                          24
#define T_COMMA                           25
#define T_CLASSNAME                       26
#define T_LB                              27
#define T_RB                              28
#define T_UP                              29
#define T_DOWN                            30
#define T_LEFT                            31
#define T_RIGHT                           32
#define T_CLOSE                           33
#define T_CHOP                            34
#define T_FROM                            35
#define T_TO                              36
#define T_THEN                            37
#define T_HEADING                         38
#define T_GO                              39
#define T_AT                              40
#define T_WITH                            41
#define T_SAME                            42
#define T_AS                              43
#define T_FIT                             44
#define T_BEHIND                          45
#define T_UNTIL                           46
#define T_EVEN                            47
#define T_DOT_E                           48
#define T_HEIGHT                          49
#define T_WIDTH                           50
#define T_RADIUS                          51
#define T_DIAMETER                        52
#define T_DOTTED                          53
#define T_DASHED                          54
#define T_CW                              55
#define T_CCW                             56
#define T_LARROW                          57
#define T_RARROW                          58
#define T_LRARROW                         59
#define T_INVIS                           60
#define T_THICK                           61
#define T_THIN                            62
#define T_SOLID                           63
#define T_CENTER                          64
#define T_LJUST                           65
#define T_RJUST                           66
#define T_ABOVE                           67
#define T_BELOW                           68
#define T_ITALIC                          69
#define T_BOLD                            70
#define T_ALIGNED                         71
#define T_BIG                             72
#define T_SMALL                           73
#define T_AND                             74
#define T_LT                              75
#define T_GT                              76
#define T_ON                              77
#define T_WAY                             78
#define T_BETWEEN                         79
#define T_THE                             80
#define T_NTH                             81
#define T_VERTEX                          82
#define T_TOP                             83
#define T_BOTTOM                          84
#define T_START                           85
#define T_END                             86
#define T_IN                              87
#define T_THIS                            88
#define T_DOT_U                           89
#define T_LAST                            90
#define T_NUMBER                          91
#define T_FUNC1                           92
#define T_FUNC2                           93
#define T_DIST                            94
#define T_DOT_XY                          95
#define T_X                               96
#define T_Y                               97
#define T_DOT_L                           98
